name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: go build -o ./bin/crawler ./cmd/qlub-calculator-api/main.go 

    - name: Run Unit Tests
      run: make unit-test

    runs-on: ubuntu-latest
    needs: docker

    steps:
    - name: Deploy to Kubernetes 
      run: |
        kubectl apply -f kubernetes-manifests/
